const datos = [
    {   
        id: "001",
        nombre : "Animales fantásticos: Los secretos de Dumbledore",
        tipo: "Pelicula",
        contenedor : ["seguir-viendo", "accion", "ciencia-ficcion", "pelicula"],
        categorias : ["Acción", "Ciencia Ficción"],
        estreno: "15/04/2022",
        clasificacion: "PG-13",
        duracion: "2h 23m",
        descripcion: "El profesor Albus Dumbledore sabe que el poderoso mago oscuro Gellert Grindelwald está haciendo planes para apoderarse del mundo mágico. Incapaz de detenerlo él solo, confía en el Magizoólogo Newt Scamander para dirigir un intrépido equipo de magos, brujas y un valiente panadero Muggle en una misión peligrosa, donde se encuentran con antiguos y nuevos animales y se enfrentan a una legión cada vez más numerosa de seguidores de Grindelwald.",
        imagen: "afdumbledore",
        url:"https://www.youtube.com/embed/NaEy627euAQ"
    },
    {   
        id: "002",
        nombre : "The Batman",
        tipo: "Pelicula",
        contenedor : ["seguir-viendo", "accion", "pelicula"],
        categorias : ["Acción"],
        estreno: "04/03/2022",
        clasificacion: "PG-13",
        duracion: "2h 56m",
        descripcion: "Cuando un asesino se dirige a la élite de Gotham con una serie de maquinaciones sádicas, un rastro de pistas crípticas envía Batman a una investigación en los bajos fondos. A medida que las pruebas comienzan a acercarse a su casa y se hace evidente la magnitud de los planes del autor, Batman debe forjar nuevas relaciones, desenmascarar al culpable y hacer justicia al abuso de poder y la corrupción que durante mucho tiempo han asolado Gotham City.",
        imagen: "batman",
        url:"https://www.youtube.com/embed/FUP3P9_mqvA",
    },
    {   
        id: "003",
        nombre : "Culto de chucky",
        tipo: "Pelicula",
        contenedor : ["seguir-viendo", "terror", "drama", "pelicula"],
        categorias : ["Terror", "Drama"],
        estreno: "23/10/2017",
        clasificacion: "R",
        duracion: "1h 35m",
        descripcion: 'Encerrada durante los últimos 4 años en un psiquiátrico, Nica Pierce está convencida erróneamente de que ella, y no Chucky, asesinó a toda su familia. Pero cuando su psiquiatra introduce una nueva "herramienta" para facilitar la sesiones en grupo de sus pacientes -un muñeco con una inocente sonrisa- empieza una cadena de extrañas muertes en el psiquiátrico, y Nica empieza a preguntarse si al final no estará tan loca como creía.',
        imagen: "chucky",
        url:"https://www.youtube.com/embed/RuIlzy7QPeM",
    },

    {   
        id: "004",
        nombre : "Doctor Strange",
        tipo: "Pelicula",
        contenedor : ["accion", "scifi", "pelicula"],
        categorias : ["Acción"],
        estreno: "23/10/2017",
        clasificacion: "R",
        duracion: "1h 35m",
        descripcion: 'Encerrada durante los últimos 4 años en un psiquiátrico, Nica Pierce está convencida erróneamente de que ella, y no Chucky, asesinó a toda su familia. Pero cuando su psiquiatra introduce una nueva "herramienta" para facilitar la sesiones en grupo de sus pacientes -un muñeco con una inocente sonrisa- empieza una cadena de extrañas muertes en el psiquiátrico, y Nica empieza a preguntarse si al final no estará tan loca como creía.',
        imagen: "drstrange",
        url:"https://www.youtube.com/embed/zJINUsjyFf8",
    },
    {   
        id: "005",
        nombre : "Doctor Strange en el multiverso de la locura",
        tipo: "Pelicula",
        contenedor : ["accion", "scifi", "pelicula"],
        categorias : ["Acción", "Ciencia Ficción"],
        estreno: "6/5/2022",
        clasificacion: "PG-13",
        duracion: "2h 6m",
        descripcion: 'Viaja a lo desconocido con el Doctor Strange, quien, con la ayuda de tanto antiguos como nuevos aliados místicos, recorre las complejas y peligrosas realidades alternativas del multiverso para enfrentarse a un nuevo y misterioso adversario.',
        imagen: "drstrange2",
        url:"https://www.youtube.com/embed/KREBGtEeW9U",
    },
    {   
        id: "006",
        nombre : "Stranger Things",
        tipo: "Serie",
        contenedor : ["drama", "scifi","serie"],
        categorias : ["Drama", "Ciencia Ficción"],
        estreno: "20/10/2016",
        clasificacion: "14",
        duracion: "50m",
        descripcion: 'A raíz de la desaparición de un niño, un pueblo desvela un misterio relacionado con experimentos secretos, fuerzas sobrenaturales aterradoras y una niña muy extraña.',
        imagen: "sthings",
        url:"https://www.youtube.com/embed/x7Yq9MJUqjY",
        temporadas: 4,
        capitulos: [8, 9, 8, 9]
    },
    {   
        id: "007",
        nombre : "Garra",
        tipo: "Pelicula",
        contenedor : ["drama", "comedia", "pelicula"],
        categorias : ["Drama", "Comedia"],
        estreno: "3/6/2022",
        clasificacion: "R",
        duracion: "1h 57m",
        descripcion: 'Encerrada durante los últimos 4 años en un psiquiátrico, Nica Pierce está convencida erróneamente de que ella, y no Chucky, asesinó a toda su familia. Pero cuando su psiquiatra introduce una nueva "herramienta" para facilitar la sesiones en grupo de sus pacientes -un muñeco con una inocente sonrisa- empieza una cadena de extrañas muertes en el psiquiátrico, y Nica empieza a preguntarse si al final no estará tan loca como creía.',
        imagen: "garrap",
        url:"https://www.youtube.com/embed/lvRWUIUoaqU",
    },
    {   
        id: "008",
        nombre : "Halo",
        tipo: "Serie",
        contenedor : ["seguir-viendo", "accion", "serie"],
        categorias : ["Accion"],
        estreno: "23/10/2017",
        clasificacion: "R",
        duracion: "60m",
        descripcion: 'Halo es una de las franquicias más populares del mundo de los videojuegos. La historia principal se centra en un conflicto interestelar entre los humanos y unos alienígenas guiados por unos profetas obsesionados con una antigua especie conocida como los Forerunners.',
        imagen: "haloo",
        url:"https://www.youtube.com/embed/u7oRIRn3mc4",
        temporadas: 1,
        capitulos: [9]
    },
    {   
        id: "009",
        nombre : "Perdidos en el Ártico",
        tipo: "Pelicula",
        contenedor : ["seguir-viendo", "drama","serie"],
        categorias : ["Drama"],
        estreno: "2/3/2022",
        clasificacion: "R",
        duracion: "1h 41m",
        descripcion: 'Basada en hechos reales. 1909. La expedición danesa Alabama, liderada por el Capitán Ejnar Mikkelsen (Coster-Waldau) emprende una misión para demostrar que Groenlandia no está dividida en dos trozos de tierra y refutar el reclamo de Estados Unidos sobre el territorio. Dejando atrás a su tripulación, le acompañará en el viaje, que llegarán a realizar incluso a pie por el hielo, el inexperto Iver Iversen (Joe Cole). ',
        imagen: "again",
        url:"https://www.youtube.com/embed/KEf1XUQefq4",
    },
    {   
        id: "010",
        nombre : "Bailando por la vida",
        tipo: "Pelicula",
        contenedor : ["comedia", "drama", "pelicula"],
        categorias : ["Comedia", "Drama"],
        estreno: "17/6/2022",
        clasificacion: "R",
        duracion: "1h 47m",
        descripcion: 'A Andrew, un joven de 22 años recién salido de la universidad que no sabe qué hacer con su vida, no le queda más remedio que volver con su familia a Nueva Jersey. Todo un experto en montar un buen sarao, consigue un trabajo de animador en las fiestas de bar mitzva de los compañeros de clase de su hermano pequeño. Cuando se hace amigo de una mujer llamada Domino y su hija Lola, que tiene un ligero autismo, Andrew descubre el futuro que desea realmente... aunque puede que no sea el suyo.',
        imagen: "cha",
        url:"https://www.youtube.com/embed/xAOra7CfMBI",
    },
    {   
        id: "011",
        nombre : "Cangrejo Negro",
        tipo: "Pelicula",
        contenedor : ["seguir-viendo", "accion", "pelicula"],
        categorias : ["Acción"],
        estreno: "18/3/2022",
        clasificacion: "R",
        duracion: "1h 52m",
        descripcion: 'Para poner fin a una guerra apocalíptica y salvar a su hija, una soldado emprende una misión desesperada: transportar un cargamento ultrasecreto por un mar helado.',
        imagen: "cangrejo",
        url:"https://www.youtube.com/embed/w3MXBceDCAo",
    },
    {   
        id: "012",
        nombre : "El aparcacoches ",
        tipo: "Pelicula",
        contenedor : ["drama", "comedia", "pelicula"],
        categorias : ["Drama", "Comedia"],
        estreno: "17/6/2022 ",
        clasificacion: "R",
        duracion: "2h 4m",
        descripcion: 'La mundialmente famosa estrella de cine Olivia enfrenta un desastre de relaciones públicas cuando un paparazzi le toma una foto con su amante casado, Vincent. El aparcacoches Antonio aparece accidentalmente en la misma foto y se alista para hacerse pasar por el nuevo novio de Olivia como un encubrimiento. Esta artimaña con Olivia empuja a Antonio al centro de atención y al caos inesperado.        ',
        imagen: "valet",
        url:"https://www.youtube.com/embed/WFlfBo_GE5c",
    },
    {   
        id: "013",
        nombre : "El páramo ",
        tipo: "Pelicula",
        contenedor : ["terror", "drama", "pelicula"],
        categorias : ["Drama", "Terror"],
        estreno: "23/10/2017",
        clasificacion: "R",
        duracion: "1h 35m",
        descripcion: 'Encerrada durante los últimos 4 años en un psiquiátrico, Nica Pierce está convencida erróneamente de que ella, y no Chucky, asesinó a toda su familia. Pero cuando su psiquiatra introduce una nueva "herramienta" para facilitar la sesiones en grupo de sus pacientes -un muñeco con una inocente sonrisa- empieza una cadena de extrañas muertes en el psiquiátrico, y Nica empieza a preguntarse si al final no estará tan loca como creía.',
        imagen: "paramo",
        url:"https://www.youtube.com/embed/VrCzupeWvuY",
    },
    {   
        id: "014",
        nombre : "El privilegio",
        tipo: "Pelicula",
        contenedor : ["terror", "pelicula"],
        categorias : ["Terror"],
        estreno: "9/2/2022",
        clasificacion: "R",
        duracion: "1h 47m",
        descripcion: 'Un adolescente acomodado y sus amigos, alumnos de un instituto de élite, destapan una siniestra conspiración mientras investigan una serie de extraños eventos sobrenaturales.',
        imagen: "privi",
        url:"https://www.youtube.com/embed/YVPpwFiaKgs",
    },
    {   
        id: "015",
        nombre : "El rescate de Ruby ",
        tipo: "Pelicula",
        contenedor : ["drama", "pelicula"],
        categorias : ["Drama"],
        estreno: "17/3/2022",
        clasificacion: "R",
        duracion: "1h 33m",
        descripcion: 'Ruby tiene mucha energía. Su dueño original la entregó a la Sociedad de Rhode Island para la Prevención de la Crueldad hacia los Animales debido a su personalidad generalmente "ingobernable".',
        imagen: "ruby",
        url:"https://www.youtube.com/embed/h5NffRxpvHY",
    },
    {   
        id: "016",
        nombre : "Elige o muere",
        tipo: "Pelicula",
        contenedor : ["drama", "terror", "pelicula"],
        categorias : ["Drama", "Terror"],
        estreno: "15/4/2022",
        clasificacion: "NR",
        duracion: "1h 25m",
        descripcion: 'Una universitaria arruinada decide jugar a un oscuro juego de ordenador de supervivencia de los años 80, en busca de un premio no reclamado de 125.000 dólares. Pero el juego la maldice y se enfrenta a peligrosas decisiones y a retos que alteran su realidad. Tras una serie de momentos inesperadamente aterradores, se da cuenta de que ya no juega por el dinero, sino por su vida.',
        imagen: "elige",
        url:"https://www.youtube.com/embed/_x0xaPSYc1U",
    },
    {   
        id: "017",
        nombre : "Incompatibles 2 ",
        tipo: "Pelicula",
        contenedor : ["comedia", "accion", "pelicula"],
        categorias : ["Comedia", "Acción"],
        estreno: "6/5/2022",
        clasificacion: "16",
        duracion: "1h 59m",
        descripcion: 'Encerrada durante los últimos 4 años en un psiquiátrico, Nica Pierce está convencida erróneamente de que ella, y no Chucky, asesinó a toda su familia. Pero cuando su psiquiatra introduce una nueva "herramienta" para facilitar la sesiones en grupo de sus pacientes -un muñeco con una inocente sonrisa- empieza una cadena de extrañas muertes en el psiquiátrico, y Nica empieza a preguntarse si al final no estará tan loca como creía.',
        imagen: "incon",
        url:"https://www.youtube.com/embed/uNkp38SCgrM",
    },
    {   
        id: "018",
        nombre : "Interceptor",
        tipo: "Pelicula",
        contenedor : ["accion", "pelicula"],
        categorias : ["Acción"],
        estreno: "26/5/2022",
        clasificacion: "MA15+",
        duracion: "1h 36m",
        descripcion: 'Una teniente del ejército usa sus años de entrenamiento táctico para salvar a la humanidad de dieciséis misiles nucleares lanzados contra los EE. UU. mientras un violento ataque coordinado amenaza simultáneamente su estación remota de interceptores de misiles.',
        imagen: "inter",
        url:"https://www.youtube.com/embed/SO-86QoQfDo",
    },
    {   
        id: "019",
        nombre : "Jurassic World: Dominion",
        tipo: "Pelicula",
        contenedor : ["accion", "scifi", "pelicula"],
        categorias : ["Acción", "Ciencia ficción"],
        estreno: "2/6/2022",
        clasificacion: "PG-13",
        duracion: "2h 26m",
        descripcion: 'Cuatro años después de la destrucción de Isla Nublar, los dinosaurios conviven – y cazan – con los seres humanos en todo el mundo. Este frágil equilibrio cambiará el futuro y decidirá, de una vez por todas, si los seres humanos seguirán en la cúspide de los depredadores en un planeta que comparten con los animales más temibles de la creación.',
        imagen: "jurasi",
        url:"https://www.youtube.com/embed/qehG9dKVDG4",
    },
    {   
        id: "020",
        nombre : "La Matanza de Texas",
        tipo: "Pelicula",
        contenedor : ["terror", "pelicula"],
        categorias : ["Terror"],
        estreno: "18/2/2022",
        clasificacion: "R",
        duracion: "1h 23m",
        descripcion: 'Melody (Sarah Yarkin), su hermana adolescente Lila (Elsie Fisher) y sus amigos Dante (Jacob Latimore) y Ruth (Nell Hudson) viajan al remoto pueblo de Harlow (Texas) para montar un negocio muy idealista. Pero su sueño se convierte en una auténtica pesadilla cuando molestan sin querer a Leatherface, el desquiciado asesino en serie cuyo sangriento legado sigue acechando a los habitantes de la zona, entre ellos Sally Hardesty (Olwen Fouéré), la única superviviente de su masacre de 1973, decidida a vengarse a muerte.        ',
        imagen: "masa",
        url:"https://www.youtube.com/embed/p8XWtiIvfAo",
    },

    {   
        id: "021",
        nombre : "La memoria de un asesino",
        tipo: "Pelicula",
        contenedor : ["seguir-viendo", "accion", "pelicula"],
        categorias : ["Acción"],
        estreno: "29/4/2022 ",
        clasificacion: "R",
        duracion: "1h 35m",
        descripcion: 'Alex, un asesino a sueldo, descubre que se ha convertido en un objetivo después de que se niega a completar un trabajo para una peligrosa organización criminal. Con el sindicato del crimen y el FBI persiguiéndolo, Alex tiene las habilidades para mantenerse a la vanguardia, excepto por una cosa: está luchando con una pérdida de memoria severa que afecta todos sus movimientos. Alex debe cuestionar cada una de sus acciones y en quién puede confiar en última instancia.',
        imagen: "memory",
        url:"https://www.youtube.com/embed/50s-JEK_XQM",
    },

    {   
        id: "022",
        nombre : "Morbius",
        tipo: "Pelicula",
        contenedor : ["accion", "scifi", "pelicula"],
        categorias : ["Acción", "Ciencia ficción"],
        estreno: "1/4/2022",
        clasificacion: "PG-13",
        duracion: "1h 45m",
        descripcion: 'Peligrosamente enfermo de un extraño trastorno sanguíneo, y determinado a salvar a otras personas que padecen su mismo destino, el doctor Morbius intenta una apuesta desesperada. Lo que en un principio parece ser un éxito radical, pronto se revela como un remedio potencialmente peor que la enfermedad. ',
        imagen: "morbius",
        url:"https://www.youtube.com/embed/C4XP8FSqTTE",
    },

    {   
        id: "023",
        nombre : "¡Nop!",
        tipo: "Pelicula",
        contenedor : ["terror", "scifi", "pelicula"],
        categorias : ["Terror", "Ciencia ficción"],
        estreno: "22/7/2022 ",
        clasificacion: "R",
        duracion: "2h 15m",
        descripcion: 'Los residentes en una quebrada solitaria del interior de California son testigos de un descubrimiento extraño y escalofriante.        ',
        imagen: "nope",
        url:"https://www.youtube.com/embed/yNgyHaegaDc",
    },
    {   
        id: "024",
        nombre : "Obi-Wan Kenobi ",
        tipo: "Serie",
        contenedor : ["seguir-viendo", "scifi", "accion","serie"],
        categorias : ["Acción", "Ciencia ficción"],
        estreno: "23/10/2017",
        clasificacion: "+14",
        duracion: "45m",
        descripcion: 'Bajo el dominio del Imperio, Obi-Wan Kenobi decide emprender una misión trascendental.',
        imagen: "obiwan",
        url:"https://www.youtube.com/embed/9lYU7bbD9Yc",
        temporadas: 1,
        capitulos: [6]
    },
    {   
        id: "025",
        nombre : "Ojos de fuego",
        tipo: "Pelicula",
        contenedor : ["seguir-viendo", "terror", "pelicula"],
        categorias : ["Terror"],
        estreno: "13/5/2022",
        clasificacion: "R",
        duracion: "1h 34m",
        descripcion: 'Andy y Vicky son unos padres que llevan más de una década huyendo en un desesperado intento de esconder a su hija Charlie de una oscura agencia estadounidense empeñada en aprovechar su increíble don para convertir el fuego en un arma de destrucción masiva. Andy enseñó a Charlie cómo dominar su extraño poder, desencadenado normalmente por la ira o el dolor. Pero cuando Charlie cumple 11 años, el fuego es cada vez más difícil de controlar. Después de que un incidente inesperado revele la ubicación de la familia, un misterioso operario sale en busca de Charlie para hacerse con ella de una vez por todas. Pero Charlie tiene otros planes.',
        imagen: "ojos",
        url:"https://www.youtube.com/embed/GkUTq5Ui6DA",
    },
    {   
        id: "026",
        nombre : "Red",
        tipo: "Pelicula",
        contenedor : ["seguir-viendo", "comedia", "pelicula"],
        categorias : ["Comedia"],
        estreno: "10/3/2022",
        clasificacion: "PG",
        duracion: "1h 35m",
        descripcion: 'Mei Lee, una niña de 13 años un poco rara pero segura de sí misma, se debate entre ser la hija obediente que su madre quiere que sea y el caos propio de la adolescencia. Ming, su protectora y ligeramente exigente madre, no se separa nunca de ella lo que es una situación poco deseable para una adolescente. Y por si los cambios en su vida y en su cuerpo no fueran suficientes, cada vez que se emociona demasiado (lo que le ocurre prácticamente todo el tiempo), se convierte en un panda rojo gigante.',
        imagen: "redd",
        url:"https://www.youtube.com/embed/upGoAejd7LM",
    },
    {   
        id: "027",
        nombre : "Sin respiro",
        tipo: "Pelicula",
        contenedor : ["accion", "pelicula"],
        categorias : ["Acción"],
        estreno: "25/2/2022",
        clasificacion: "R",
        duracion: "1h 35m",
        descripcion: 'Después de hacer lo indecible para encubrir un accidente, un policía corrupto pierde el control de su vida cuando comienza a recibir amenazas de un misterioso testigo.',
        imagen: "respiro",
        url:"https://www.youtube.com/embed/TfKIFiwNkrU",
    },
    {   
        id: "028",
        nombre : "Scream 5",
        tipo: "Pelicula",
        contenedor : ["terror", "pelicula"],
        categorias : ["Terror"],
        estreno: "13/1/2022 ",
        clasificacion: "R",
        duracion: "2h",
        descripcion: 'Una nueva entrega de la saga de terror ‘Scream’ que seguirá a una mujer que regresa a su ciudad natal para intentar descubrir quién ha estado cometiendo una serie de crímenes atroces.',
        imagen: "scremm",
        url:"https://www.youtube.com/embed/8lm7nR-xRqA",
    },
    {   
        id: "029",
        nombre : "The Contractor",
        tipo: "Pelicula",
        contenedor : ["accion", "pelicula"],
        categorias : ["Acción"],
        estreno: "23/10/2017",
        clasificacion: "SG",
        duracion: "1h 43m",
        descripcion: 'Después de ser dado de baja involuntariamente de las Fuerzas Especiales de EE. UU., James Harper decide apoyar a su familia uniéndose a una organización de contratación privada junto a su mejor amigo y bajo el mando de un compañero veterano. En el extranjero en una misión encubierta, Harper debe evadir a quienes intentan matarlo mientras regresa a casa.',
        imagen: "elite",
        url:"https://www.youtube.com/embed/ZCPIB9VywKw",
    },
    {   
        id: "030",
        nombre : "Sonic 2",
        tipo: "Pelicula",
        contenedor : ["accion", "comedia", "pelicula"],
        categorias : ["Acción", "Comedia"],
        estreno: "26/06/2020",
        clasificacion: "R",
        duracion: "1h 39m",
        descripcion: 'Encerrada durante los últimos 4 años en un psiquiátrico, Nica Pierce está convencida erróneamente de que ella, y no Chucky, asesinó a toda su familia. Pero cuando su psiquiatra introduce una nueva "herramienta" para facilitar la sesiones en grupo de sus pacientes -un muñeco con una inocente sonrisa- empieza una cadena de extrañas muertes en el psiquiátrico, y Nica empieza a preguntarse si al final no estará tan loca como creía.Sonic intenta navegar por las complejidades de la vida en la Tierra con su nuevo mejor amigo, un humano llamado Tom Wachowski. Pronto deben unir fuerzas para evitar que el malvado Dr. Robotnik capture a Sonic y use sus poderes para dominar el mundo.',
        imagen: "sonicc",
        url:"https://www.youtube.com/embed/2OMixTIRQcY",
    },
    {   
        id: "031",
        nombre : "The Flash",
        tipo: "Serie",
        contenedor : ["scifi", "drama","serie"],
        categorias : ["Drama", "Ciencia ficcion"],
        estreno: "23/10/2017",
        clasificacion: "R",
        duracion: "1h 35m",
        descripcion: 'Nueve meses después de que el laboratorio S.T.A.R. explotara, Barry despierta del coma y descubre que tiene el poder de la súper velocidad. Con la ayuda de su nuevo equipo, Barry, denominado ahora `Flash, luchará contra el crimen en Ciudad Central. ',
        imagen: "tflash",
        url:"https://www.youtube.com/embed/_l9HkDJnwLw",
        temporadas: 8,
        capitulos: [23, 23, 23, 23, 22, 19, 18, 20]
    },
    {   
        id: "032",
        nombre : "The Good Doctor",
        tipo: "Serie",
        contenedor : ["drama", "serie"],
        categorias : ["Drama"],
        estreno: "25/09/2017",
        clasificacion: "R",
        duracion: "1h 35m",
        descripcion: 'Un cirujano joven y autista que padece el síndrome del sabio empieza a trabajar en un hospital prestigioso. Allá tendrá que vencer el escepticismo con el que sus colegas lo reciben.',
        imagen: "doctor",
        url:"https://www.youtube.com/embed/vHns_LJeFhg",
        temporadas: 5,
        capitulos: [18, 18, 20, 20, 18]
    },
    {   
        id: "033",
        nombre : "La mujer del viajero en el tiempo",
        tipo: "Serie",
        contenedor : ["scifi","drama", "pelicula"],
        categorias : ["Ciencia Ficción", "Drama"],
        estreno: "15/05/2022",
        clasificacion: "R",
        duracion: "1h 35m",
        descripcion: 'La compleja y mágica historia de amor de Claire y Henry, un matrimonio afectado por un enorme problema: los viajes en el tiempo.',
        imagen: "tiempo",
        url:"https://www.youtube.com/embed/GoPAoYSkOkw",
        temporadas: 1,
        capitulos: [6]
    },
    {   
        id: "034",
        nombre : "The walking dead: El principio del fin",
        tipo: "Serie",
        contenedor : ["accion", "drama", "scifi","serie"],
        categorias : ["Acción", "Drama", "Ciencia ficción"],
        estreno: "2/11/2015",
        clasificacion: "R",
        duracion: "1h 30m",
        descripcion: 'Negan, Daryl, Carol y Maggie afrontan el final como supervivientes principales de una ficción marcada por las salidas de sus rostros más emblemáticos. Idas y venidas de personajes clave que han obligado a la serie a reinventarse en más ocasiones de lo previsto y soportable, y que provocan que aborde el desenlace como un producto bien diferente al que era en sus inicios.',
        imagen: "dead",
        url:"https://www.youtube.com/embed/R1v0uFms68U",
        temporadas: 11,
        capitulos: [6, 13, 16, 16, 16, 16, 16, 16, 16, 22, 16]
    },
    {   
        id: "035",
        nombre : "Uncharted",
        tipo: "Pelicula",
        contenedor : ["seguir-viendo", "accion", "pelicula"],
        categorias : ["Acción"],
        estreno: "18/2/2022",
        clasificacion: "PG-13",
        duracion: "1h 35m",
        descripcion: 'Un descendiente del famoso corsario Sir Francis Drake descubre la ubicación de la legendaria ciudad de El Dorado. Con la ayuda de su mentor Victor Sullivan y la ambiciosa periodista Elena Fischer, Nathan Drake trabajará para descubrir sus secretos, mientras sobreviven en una isla llena de piratas, mercenarios, y un misterioso enemigo, se embarcarán en una búsqueda sin precedentes por alcanzar el tesoro antes que sus perseguidores. Adaptación del aclamado videojuego homónimo.',
        imagen: "charter",
        url:"https://www.youtube.com/embed/kVgsnqAp0Kk",
    },
    {   
        id: "036",
        nombre : "Venganza a golpes",
        tipo: "Pelicula",
        contenedor : ["accion", "pelicula"],
        categorias : ["Acción"],
        estreno: "17/2/20227",
        clasificacion: "R",
        duracion: "1h 34m",
        descripcion: 'Kai Jin, un joven chef de Chinatown en la actual San Francisco, se ve envuelto en la búsqueda de la Tríada China de poderes ancestrales mortales conocidos como el "Wu Xing".',
        imagen: "golpes",
        url:"https://www.youtube.com/embed/pKLogozB_oI",
    },
    {   
        id: "037",
        nombre : "Spiderhead ",
        tipo: "Pelicula",
        contenedor : ["scifi", "pelicula"],
        categorias : ["Ciencia ficción"],
        estreno: "17/6/2022",
        clasificacion: "R",
        duracion: "1h 46m",
        descripcion: 'En un futuro próximo, se ofrece a presidiarios la oportunidad de someterse a experimentos médicos para acortar su sentencia. Uno de los sujetos, inyectado con una droga que genera sentimientos de amor, empieza a cuestionar sus emociones.',
        imagen: "head",
        url:"https://www.youtube.com/embed/2izML8QwXrw",
    },
    {   
        id: "038",
        nombre : "Lightyear",
        tipo: "Pelicula",
        contenedor : ["scifi", "accion", "pelicula"],
        categorias : ["Ciencia ficción", "Acción"],
        estreno: "17/06/2022",
        clasificacion: "PG",
        duracion: "1h 47m",
        descripcion: 'Atrapado en un planeta hostil a 4,2 millones de años luz de la Tierra junto a su comandante y su tripulación, Buzz Lightyear intenta encontrar la manera de volver a casa a través del espacio y el tiempo. Pero la llegada de Zurg, una presencia imponente con un ejército de robots despiadados y una agenda misteriosa, complica aún más las cosas y pone en peligro la misión.',
        imagen: "year",
        url:"https://www.youtube.com/embed/orYSANFnv9M",
    },
    {   
        id: "039",
        nombre : "Hotel Transilvania: Transformanía",
        tipo: "Pelicula",
        contenedor : ["comedia", "pelicula"],
        categorias : ["Comedia"],
        estreno: "25/2/2022",
        clasificacion: "PG",
        duracion: "1h 27m",
        descripcion: 'Drac y la pandilla vuelven, como nunca los habías visto antes en Hotel Transilvania: Transformanía. Volveremos a encontrarnos con nuestros monstruos favoritos en una aventura completamente nueva en la que Drac se enfrentará a una de las situaciones más aterradoras vividas hasta el momento. Cuando el misterioso invento de Van Helsing, el "Rayo Monstrificador", se vuelve totalmente fuera de control, Drac y sus monstruosos amigos se transforman en humanos, ¡y Johnny se convierte en un monstruo!',
        imagen: "tran",
        url:"https://www.youtube.com/embed/J5Xp3Flbj9k",
    },
    {   
        id: "040",
        nombre : "Peaky Blinders",
        tipo: "Serie",
        contenedor : ["drama","serie"],
        categorias : ["Drama"],
        estreno: "2/10/2013",
        clasificacion: "R",
        duracion: "52m",
        descripcion: 'Narra la historia de la familia gitana Shelby y su banda de gángsters, un grupo de personas características por sus boinas con cuchillas y dueñas de los asuntos ilegales, que dominan las apuestas clandestinas y se rigen mediante extorsiones.', 
        imagen: "pblinders",   
        url:"https://www.youtube.com/embed/_l9HkDJnwLw",
        temporadas: 6,
        capitulos: [6, 6, 6, 6, 6, 6]
    },
]
